services:
  # CORS proxy service (original)
  - type: web
    name: tubingen-feedback-cors-proxy
    runtime: node
    buildCommand: npm install
    startCommand: node cors-proxy.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: OPENAI_API_KEY
        sync: false
  
  # Simplified version - Task→Survey→Task→Survey flow (NEW)
  - type: web
    name: infer-task-survey
    runtime: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: ./infer-task-survey-version
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 