services:
  # Static web app service for the frontend
  - type: web
    name: tubingen-feedback-tool
    runtime: static
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x

  # Web service for the CORS proxy
  - type: web
    name: tubingen-feedback-cors-proxy
    runtime: node
    buildCommand: npm install
    startCommand: node cors-proxy.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: OPENAI_API_KEY
        sync: false 