services:
  # Single web service that handles both CORS proxy AND serves the frontend
  - type: web
    name: tubingen-feedback-cors-proxy
    runtime: node
    buildCommand: npm install
    startCommand: node cors-proxy.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: OPENAI_API_KEY
        sync: false 